# Generated by Django 4.2.13 on 2024-06-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momttokback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babydata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mainpg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mypg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
