# Generated by Django 4.2.13 on 2024-06-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momttokback', '0002_alter_babydata_options_alter_calendar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babydata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mainpg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mypg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
